const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)}
function glow(c,x,y,rx,ry,stops){const gr=c.createRadialGradient(x,y,0,x,y,Math.max(rx,ry));stops.forEach(s=>gr.addColorStop(s[0],s[1]));c.save();c.translate(x,y);c.scale(1,ry/rx);c.fillStyle=gr;c.beginPath();c.arc(0,0,rx,0,Math.PI*2);c.fill();c.restore()}
async function showScreen(id){if(document.fullscreenElement&&document.fullscreenElement.id!==id){try{await document.exitFullscreen()}catch{}}$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});location.hash=id==='home'?'':id;if(id==='game0')renderG0();if(id==='game3')drawResolution();if(id==='game4')drawInterferometer()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));
$$('[data-fullscreen]').forEach(button=>button.addEventListener('click',async()=>{const target=$(button.dataset.fullscreen);try{if(document.fullscreenElement===target)await document.exitFullscreen();else await target.requestFullscreen()}catch{toast('Full screen is unavailable in this browser.')}}));
function syncFullscreenButtons(){$$('[data-fullscreen]').forEach(button=>{const active=document.fullscreenElement?.id===button.dataset.fullscreen;button.querySelector('strong').textContent=active?'Exit full screen':'Full screen';button.setAttribute('aria-label',active?'Exit full screen':'Enter full screen');button.setAttribute('aria-pressed',String(active))})}
document.addEventListener('fullscreenchange',syncFullscreenButtons);
syncFullscreenButtons();

// Game 0: learn to read angular sizes and scale bars
const g0Steps=[
 {label:'SKY → IMAGE',kicker:'FROM DIRECTIONS TO PIXELS',title:'An astronomy image maps directions in the sky onto positions in a picture.',copy:'The angle θ is the gap between two directions as seen by the observer. In an image, those directions appear at two different positions. Each pixel covers a known angle, such as 0.5 arcseconds per pixel. Across a small part of the image, this lets us measure θ.',question:'What does θ measure?',takeaway:'The angle covered by one pixel connects distances in a 2D image to directions in the sky. A scale bar shows this information in an easy form.',visual:'projection',answers:[['How far apart the two sources appear in the sky',true,'Correct. This is their angular separation. If they are 10 pixels apart and each pixel covers 0.5 arcseconds, then θ is 5 arcseconds.'],['The true distance between the two sources',false,'That is a physical distance, such as kilometres or light-years. θ measures how far apart they appear in the sky.'],['How bright the two sources appear',false,'Brightness measures signal strength. θ measures angular separation.']]},
 {label:'ANGLE UNITS',kicker:'READ THE SYMBOL',title:'The marks ′ and ″ describe angles.',copy:'One degree is divided into 60 equal arcminutes. One arcminute is divided into 60 equal arcseconds.',question:'Which name matches the symbol 1″?',takeaway:'° means degree, ′ means arcminute and ″ means arcsecond.',visual:'units',answers:[['One arcsecond',true,'Correct. The double mark ″ means one arcsecond.'],['One arcminute',false,'One arcminute uses the single mark ′.'],['One second of time',false,'In an astronomy image, this mark describes an angle rather than an amount of time.']]},
 {label:'CYGNUS A + SCALE BAR',kicker:'MEET THE SOURCE, THEN MEASURE IT',title:'Cygnus A is a powerful radio galaxy.',copy:'Cygnus A is about 750 million light-years away. Matter falling towards its central supermassive black hole powers two jets. The jets carry energy far into space and inflate the two large radio lobes seen in this image. Each white scale-bar section represents approximately 1 arcminute, estimated from the published separation of the terminal hotspots.',question:'About how wide does Cygnus A appear in the sky?',takeaway:'Compare the source with the labelled scale bar. Two bars show an angular width of about 2 arcminutes.',visual:'scale',answers:[['About 2 arcminutes',true,'Correct. The radio source spans roughly two scale-bar sections, each representing about 1 arcminute.'],['About 2 arcseconds',false,'Look at the symbol on the scale bar. It is 1′, which means 1 arcminute.'],['About 2 light-years',false,'The scale bar gives an apparent angle in the sky. It does not give the true width in light-years.']]},
 {label:'M87* · TINY DETAIL',kicker:'READ TWO SIZES ON ONE IMAGE',title:'The bright ring around M87* appears about 42 μas wide.',copy:'The Event Horizon Telescope made this image with a resolution of about 20 microarcseconds. Resolution is the smallest angular detail that the observation can separate.',question:'What is the smallest detail this image can separate?',takeaway:'The ring is about 42 microarcseconds wide. The image can separate details of about 20 microarcseconds.',visual:'detail',answers:[['2 arcmin',false,'That angle is far larger than the whole ring.'],['0.5 arcsec',false,'This is still much larger than the ring around M87*.'],['20 μas',true,'Correct. The marked image resolution is about 20 microarcseconds.']]},
];
let g0Step=0,g0Solved=new Set();
function g0VisualMarkup(type){
 if(type==='projection')return '<div class="g0-projection"><svg class="g0-projection-svg" viewBox="0 0 1000 420" preserveAspectRatio="xMidYMid meet" role="img" aria-label="A side view of two sky directions separated by angle theta, followed by a pixel grid where the same angular separation theta lies between two image positions"><rect class="proj-panel" x="18" y="18" width="442" height="384" rx="10"/><text class="proj-head" x="42" y="54">SIDE VIEW OF THE SKY ANGLE</text><circle class="proj-eye" cx="82" cy="210" r="25"/><circle class="proj-pupil" cx="89" cy="210" r="8"/><line class="proj-ray" x1="82" y1="210" x2="408" y2="100"/><line class="proj-ray" x1="82" y1="210" x2="408" y2="320"/><circle class="proj-source" cx="408" cy="100" r="20"/><circle class="proj-source" cx="408" cy="320" r="20"/><path class="proj-angle" d="M157.8 184.4 A80 80 0 0 1 157.8 235.6"/><text class="proj-theta" x="171" y="219">θ</text><text class="proj-note" x="92" y="374">angle between two sky directions</text><path class="proj-arrow" d="M477 210 H517 M503 195 L518 210 L503 225"/><rect class="proj-panel" x="536" y="18" width="446" height="384" rx="10"/><text class="proj-head" x="560" y="54">2D TELESCOPE IMAGE</text><rect class="proj-detector" x="577" y="76" width="360" height="270" rx="4"/><path class="proj-pixel-grid" d="M622 76V346 M667 76V346 M712 76V346 M757 76V346 M802 76V346 M847 76V346 M892 76V346 M577 121H937 M577 166H937 M577 211H937 M577 256H937 M577 301H937"/><rect class="proj-one-pixel" x="847" y="76" width="45" height="45"/><text class="proj-pixel-label" x="748" y="70">PIXEL SIZE</text><path class="proj-pixel-pointer" d="M828 66 L868 92"/><circle class="proj-image-dot" cx="734.5" cy="143.5" r="16"/><circle class="proj-image-dot" cx="734.5" cy="278.5" r="16"/><line class="proj-bracket" x1="792" y1="143.5" x2="792" y2="278.5"/><line class="proj-bracket" x1="782" y1="143.5" x2="802" y2="143.5"/><line class="proj-bracket" x1="782" y1="278.5" x2="802" y2="278.5"/><text class="proj-theta" x="812" y="220">θ</text><text class="proj-note" x="584" y="378">θ ≈ number of pixels × angle per pixel</text></svg></div>';
 if(type==='units')return '<div class="g0-unit-ladder" aria-label="A ladder of progressively smaller angle symbols"><div><b>1°</b></div><i>÷ 60</i><div><b>1′</b></div><i>÷ 60</i><div><b>1″</b></div><i>÷ 1,000,000</i><div><b>1 μas</b></div></div>';
 if(type==='scale')return '<div class="g0-image-measure"><div class="g0-image-measure-content"><svg class="g0-scale-svg" viewBox="0 0 1024 476" role="img" aria-label="VLA radio image of Cygnus A with two approximate one-arcminute scale-bar sections"><image href="assets/cygnus-a-nrao.jpg" x="0" y="0" width="1024" height="476"/><path class="g0-scale-line" d="M58 389V409 M58 399H966 M512 389V409 M966 389V409"/><text class="g0-scale-text" x="285" y="435">≈1′</text><text class="g0-scale-text" x="739" y="435">≈1′</text></svg></div><a href="https://www.aoc.nrao.edu/~ccarilli/cyga.shtml" target="_blank" rel="noreferrer">VLA/NRAO · C. Carilli ↗</a></div>';
 if(type==='detail')return '<div class="g0-m87-measure"><div class="g0-m87-frame"><img src="assets/m87-eht.jpg" alt="Event Horizon Telescope image of the black hole M87* with its angular size marked"><a href="https://www.eso.org/public/images/eso1907a/" target="_blank" rel="noreferrer">EHT Collaboration / ESO ↗</a><div class="g0-ring-width"><i></i><strong>RING ≈ 42 μas</strong></div><div class="g0-image-detail"><span>SMALLEST DETAIL SEEN</span><strong>≈ 20 μas</strong></div></div></div>';
 return '';
}
function renderG0(){const s=g0Steps[g0Step],panel=document.querySelector('.g0-quiz-panel');$('g0VisualLabel').textContent=s.label;$('g0StepBadge').textContent=`QUESTION ${g0Step+1} OF 4`;$('g0Kicker').textContent=s.kicker;$('g0Title').textContent=s.title;$('g0Copy').textContent=s.copy;$('g0Question').textContent=s.question;$('g0Takeaway').textContent=s.takeaway;$('g0Score').textContent=`${g0Solved.size} / 4 correct`;$('g0Visual').innerHTML=g0VisualMarkup(s.visual);panel.classList.remove('answered');$('g0Feedback').className='answer-feedback';$('g0Feedback').innerHTML='';$('g0Feedback').hidden=true;$('g0Next').hidden=true;const choices=$('g0Choices');choices.innerHTML='';s.answers.forEach((a,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<b>${String.fromCharCode(65+i)}</b><strong>${a[0]}</strong>`;b.onclick=()=>answerG0(i);choices.appendChild(b)});$$('[data-g0-step]').forEach((b,i)=>{b.classList.toggle('active',i===g0Step);b.classList.toggle('done',g0Solved.has(i))})}
function answerG0(i){const a=g0Steps[g0Step].answers[i],buttons=$$('#g0Choices button'),feedback=$('g0Feedback');buttons.forEach((b,j)=>{b.classList.toggle('correct',j===i&&a[1]);b.classList.toggle('wrong',j===i&&!a[1])});document.querySelector('.g0-quiz-panel').classList.add('answered');feedback.hidden=false;feedback.className=`answer-feedback ${a[1]?'correct':'wrong'}`;feedback.innerHTML=`<strong>${a[1]?'Correct!':'Look again.'}</strong><span>${a[2]}</span>`;if(a[1]){g0Solved.add(g0Step);buttons.forEach(b=>b.disabled=true);$('g0Score').textContent=`${g0Solved.size} / 4 correct`;$('g0Next').hidden=false;$('g0Next').innerHTML=g0Solved.size===4?'Continue to Game 01 <span>→</span>':'Next question <span>→</span>';$$('[data-g0-step]')[g0Step].classList.add('done')}}
function selectG0(i){g0Step=i;renderG0()}
$$('[data-g0-step]').forEach((b,i)=>b.onclick=()=>selectG0(i));$('g0Next').onclick=()=>{if(g0Solved.size===4){showScreen('game1');return}const next=g0Steps.findIndex((_,i)=>!g0Solved.has(i));selectG0(next<0?0:next)};

// Game 1 — three image-led multiple-choice missions
const g1Missions=[
 {target:'Cygnus A',badge:'MISSION 01',type:'POWERFUL RADIO GALAXY',title:'Can your dish separate its two radio lobes?',copy:'Cygnus A is about <strong>750 million light-years away</strong>. Jets from its central black hole inflate two magnetised bubbles called radio lobes; the whole radio structure spans several hundred thousand light-years.',image:'assets/cygnus-a-nrao.jpg',alt:'VLA radio image of Cygnus A',credit:'VLA/NRAO · C. Carilli ↗',source:'https://www.aoc.nrao.edu/~ccarilli/cyga.shtml',wrap:'',scale:'1 arcmin',wave:'6 cm',detail:'≈ 1.5 arcmin',rad:'≈ 4.4 × 10⁻⁴ rad',answers:[{label:'0.025 km',note:'25 metres',ok:false,why:'It can only distinguish details about 8 arcminutes wide — larger than the whole source.'},{label:'0.15 km',note:'150 metres',ok:true,why:'Correct. Using θ ≈ 4.4 × 10⁻⁴ rad and λ = 0.06 m gives D ≈ λ/θ ≈ 140 m, so 150 m is the closest choice.'},{label:'25 km',note:'25,000 metres',ok:false,why:'It would work, but it is far larger than the smallest diameter the mission asks for.'}]},
 {target:'Cygnus A hotspot',badge:'MISSION 02',type:'WHERE A RADIO JET HITS SURROUNDING GAS',title:'What diameter would resolve an illustrative 5″ hotspot-sized feature?',copy:'The terminal hotspots are compact, only a few arcseconds across. The <strong>5″</strong> target is an approximate teaching scale, not a measured diameter of either circled hotspot. The published VLA image has <strong>0.5″ resolution</strong>, fine enough to show structure within them.',image:'assets/cygnus-a-nrao.jpg',alt:'VLA radio image of Cygnus A with terminal hotspots marked',credit:'VLA/NRAO · C. Carilli ↗',source:'https://www.aoc.nrao.edu/~ccarilli/cyga.shtml',wrap:'hotspot-view',scale:'≈ 10 arcsec',wave:'6 cm',detail:'≈ 5 arcsec',rad:'≈ 2.4 × 10⁻⁵ rad',answers:[{label:'0.12 km',note:'120 metres',ok:false,why:'At 6 cm this resolves only about 100 arcseconds, so the hotspot would blend into the lobe.'},{label:'2.5 km',note:'2,500 metres',ok:true,why:'Correct for this illustrative 5″ target. θ ≈ 2.4 × 10⁻⁵ rad and λ = 0.06 m give D ≈ λ/θ ≈ 2,500 m.'},{label:'25 km',note:'25,000 metres',ok:false,why:'This reaches about 0.5 arcsecond and reveals finer structure, but it is roughly ten times larger than this 5-arcsecond mission needs.'}]},
 {target:'M87*',badge:'MISSION 03',type:'SUPERMASSIVE BLACK-HOLE SHADOW',title:'How large must a dish be to see this ring?',copy:'M87* lies about <strong>55 million light-years away</strong> and has 6.5 billion times the Sun’s mass. Its bright ring is only about 42 microarcseconds across; EHT distinguished details around 20 microarcseconds.',image:'assets/m87-eht.jpg',alt:'Event Horizon Telescope image of the black hole M87*',credit:'EHT Collaboration / ESO ↗',source:'https://www.eso.org/public/images/eso1907a/',wrap:'m87-view',scale:'42 μas',wave:'1.3 mm',detail:'20 μas',rad:'≈ 9.7 × 10⁻¹¹ rad',answers:[{label:'36 km',note:'VLA-sized',ok:false,why:'Far too small: its smallest distinguishable detail would be thousands of times larger than the ring.'},{label:'3,000 km',note:'Continent-wide',ok:false,why:'Closer, but it can distinguish only about 90 microarcseconds at 1.3 mm.'},{label:'13,000 km',note:'Earth-wide',ok:true,why:'Correct. Using θ ≈ 9.7 × 10⁻¹¹ rad and λ = 1.3 × 10⁻³ m gives D ≈ λ/θ ≈ 1.34 × 10⁷ m, about 13,400 km.'}]}
];
let g1Mission=0,g1Solved=new Set();
function drawResolution(){renderG1Mission()}
function renderG1Mission(){const m=g1Missions[g1Mission],feedback=$('g1Feedback');$('g1Target').textContent=m.target;$('g1Badge').textContent=m.badge;$('g1ObjectType').textContent=m.type;$('g1MissionTitle').textContent=m.title;$('g1Caption').innerHTML=m.copy;$('g1Image').src=m.image;$('g1Image').alt=m.alt;$('g1ImageCredit').textContent=m.credit;$('g1ImageCredit').href=m.source;$('g1Image').parentElement.className=`g1-image-wrap ${m.wrap}`;$('g1ScaleBar').innerHTML=`<i></i>${m.scale}`;$('g1Wave').textContent=m.wave;$('g1Resolution').textContent=m.detail;$('g1ResolutionRad').textContent=m.rad;$('g1Score').textContent=`${g1Solved.size} / 3 correct`;feedback.className='answer-feedback';feedback.innerHTML='';feedback.hidden=true;$('g1Next').hidden=true;const choices=$('g1Choices');choices.innerHTML='';m.answers.forEach((a,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<b>${String.fromCharCode(65+i)}</b><strong>${a.label}</strong><span>${a.note}</span>`;b.onclick=()=>answerG1(i);choices.appendChild(b)});$$('#g1MissionList li').forEach((li,i)=>{li.classList.toggle('active',i===g1Mission);li.classList.toggle('done',g1Solved.has(i))})}
function answerG1(index){const m=g1Missions[g1Mission],answer=m.answers[index],buttons=$$('#g1Choices button'),feedback=$('g1Feedback');buttons.forEach((b,i)=>{b.classList.toggle('correct',i===index&&answer.ok);b.classList.toggle('wrong',i===index&&!answer.ok)});feedback.hidden=false;feedback.className=`answer-feedback ${answer.ok?'correct':'wrong'}`;feedback.innerHTML=`<strong>${answer.ok?'Correct!':'Not quite.'}</strong><span>${answer.why}</span>`;if(answer.ok){g1Solved.add(g1Mission);buttons.forEach(b=>b.disabled=true);$('g1Score').textContent=`${g1Solved.size} / 3 correct`;$('g1Next').hidden=false;$('g1Next').innerHTML=g1Solved.size===3?'Review from Mission 01 <span>↺</span>':'Next mission <span>→</span>';$$('#g1MissionList li')[g1Mission].classList.add('done');$('g1Reality').textContent=g1Mission===2?'A 13,000 km solid dish is impossible. Game 4 shows how many dishes imitate that diameter.':'Cygnus A bars are approximate, estimated from the published ≈130″ separation of its terminal hotspots.'}}
function selectG1Mission(i){g1Mission=i;renderG1Mission()}
$$('[data-g1-mission]').forEach(li=>{li.onclick=()=>selectG1Mission(Number(li.dataset.g1Mission));li.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();li.click()}}});$('g1Next').onclick=()=>{const next=g1Missions.findIndex((_,i)=>!g1Solved.has(i));selectG1Mission(next<0?0:next)};

// Game 2 — real registered multiwavelength images
const bands={radio:{title:'Radio',image:'assets/crab-radio.png',telescope:'KARL G. JANSKY VERY LARGE ARRAY',energy:'LOWER-ENERGY PHOTONS',question:'What information does radio add?',clue:'Long-lived, lower-energy relativistic electrons across the broad nebula',copy:'The pulsar wind supplies relativistic electrons. As they spiral in magnetic fields they emit synchrotron radiation. Electrons radiating strongly at radio wavelengths lose energy more slowly and travel farther, so radio maps the nebula’s broad outer extent.',pos:'0%'},infrared:{title:'Infrared',image:'assets/crab-infrared.png',telescope:'SPITZER SPACE TELESCOPE',energy:'DUST · LINES · SYNCHROTRON',question:'What information does infrared add?',clue:'Synchrotron emission, warm dust and emission lines from the ejecta',copy:'Spitzer’s infrared data contain several components. Synchrotron emission is strong, dust grains reradiate absorbed energy in the infrared, and ions in the expanding ejecta produce emission lines. Different infrared filters give these components different weights.',pos:'25%'},visible:{title:'Visible light',image:'assets/crab-visible.png',telescope:'HUBBLE SPACE TELESCOPE',energy:'GAS · SYNCHROTRON',question:'What information does visible light add?',clue:'Sharp, line-emitting supernova-ejecta filaments plus diffuse synchrotron light',copy:'Hubble resolves warm ionised ejecta into a tangled filament network. Emission lines from different ions reveal the gas and its composition, while diffuse light in the nebula’s interior includes synchrotron radiation from relativistic electrons.',pos:'50%'},ultraviolet:{title:'Ultraviolet',image:'assets/crab-ultraviolet.png',telescope:'XMM-NEWTON OPTICAL MONITOR',energy:'UV SYNCHROTRON',question:'What information does ultraviolet add?',clue:'Higher-energy synchrotron structure, including bays at the nebula’s edges',copy:'The ultraviolet emission seen by XMM-Newton’s Optical Monitor is thought to be synchrotron radiation. It traces a more energetic electron population than radio and reveals east–west bays where surrounding structure appears to restrict the particle-filled nebula.',pos:'75%'},xray:{title:'X-ray',image:'assets/crab-xray.png',telescope:'CHANDRA X-RAY OBSERVATORY',energy:'HIGHEST-ENERGY PHOTONS',question:'What information do X-rays add?',clue:'Freshly accelerated, highest-energy electrons and structures close to the pulsar',copy:'Chandra X-rays directly trace the highest-energy electrons supplied by the pulsar wind. These electrons radiate away energy quickly, so the X-ray nebula is compact and highlights the inner ring-like structure, jets and changing particle flow near the pulsar.',pos:'100%'}};let seen=new Set(['radio']),currentBand='radio';
function setBand(key){const b=bands[key];currentBand=key;seen.add(key);$$('[data-band]').forEach(x=>x.classList.toggle('active',x.dataset.band===key));$('crabImage').src=b.image;$('crabImage').alt=`${b.title} image of the Crab Nebula`;$('g2BandTitle').textContent=b.title;$('g2Telescope').textContent=b.telescope;$('g2Energy').textContent=b.energy;$('g2Question').textContent=b.question;$('g2Clue').querySelector('strong').textContent=b.clue;$('g2Explanation').textContent=b.copy;$('g2Meter').style.setProperty('--position',b.pos);$('g2Score').textContent=`${seen.size}/5`;if(seen.size===5)toast('All five bands explored!')}
$$('[data-band]').forEach(b=>b.onclick=()=>setBand(b.dataset.band));$('g2Compare').addEventListener('pointerdown',()=>{$('crabImage').src=bands.visible.image;$('g2Lens').classList.add('show')});['pointerup','pointerleave','pointercancel'].forEach(ev=>$('g2Compare').addEventListener(ev,()=>{$('crabImage').src=bands[currentBand].image;$('g2Lens').classList.remove('show')}));$('g2Labels').onchange=e=>$('g2Clue').hidden=!e.target.checked;$$('[data-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='xray';$('g2Feedback').textContent=ok?'Correct — X-rays trace the freshly accelerated, highest-energy electrons closest to the pulsar.':'Try again: which electrons lose energy fastest and therefore remain closest to the pulsar?';$('g2Feedback').style.color=ok?'#166e66':'#b33b25'});

// Game 2 — a simple causal story from gas to radio lobes
const steps=[
  {k:'STEP 1 · GAS MOVES IN',t:'Gas circles the black hole',c:'Gravity pulls nearby gas towards the black hole and bends its path. Because the gas is also moving around the galaxy’s centre, it goes into orbit instead of dropping straight in.',a:'The Moon keeps moving forward while Earth’s gravity bends its path into an orbit.',cap:'Gravity bends the moving gas into an orbit outside the black hole.',note:'The black hole is not blowing material out from inside. The story begins with gas outside it.',button:'Form the flow'},
  {k:'STEP 2 · A HOT FLOW FORMS',t:'A hot accretion flow forms',c:'Many rings of gas orbit the black hole; inner gas moves faster than outer gas. Turbulence lets some gas move inward and releases energy as heat and light. This hot, rotating gas is called an accretion flow. When it forms a flat shape, we call it an accretion disk.',a:'Think of two satellites orbiting Earth: the lower satellite must move faster and completes an orbit sooner than the higher one.',cap:'The glowing accretion flow is hot gas outside the black hole.',note:'This light is accretion-flow emission, not the black-hole shadow. A shadow is the dark central region seen against glowing gas on a much smaller scale.',button:'Add magnetic fields'},
  {k:'STEP 3 · FIELD LINES TWIST',t:'The rotating flow twists magnetic field lines',c:'The hot gas is plasma: it contains charged particles, so the gas and magnetic field move together. Inner gas orbits faster than outer gas, stretching and twisting the field lines. Near the centre, the twisted field forms two funnel-shaped channels along the rotation axis. These fields can help launch the jets and keep them narrow.',a:'Turn the middle of a bundle of elastic threads: the threads twist and tighten around the axis.',cap:'The turquoise curves are magnetic field lines, not the paths of individual gas clouds.',note:'This is a simplified picture. Magnetic fields are essential, but scientists are still studying how the accretion flow and the black hole’s spin work together to launch jets.',button:'Send out the jets'},
  {k:'STEP 4 · TWO JETS MOVE OUT',t:'The two jets travel in opposite directions',c:'Two narrow streams of energy and fast particles move away from the centre: one travels in one direction along the rotation axis, while the other travels in the opposite direction.',a:'Imagine two hose nozzles placed back-to-back, sending narrow streams in opposite directions.',cap:'Both jets move outward from the centre, carrying energy far into the galaxy.',note:'Nothing is escaping from inside the black hole. The two jets begin in the hot, magnetised region outside it.',button:'Grow the lobes'},
  {k:'STEP 5 · HOTSPOTS AND LOBES',t:'The jets make hotspots and inflate lobes',c:'In a powerful radio galaxy, each jet eventually crashes into surrounding gas and slows down. The bright impact zone is called a hotspot. Energy then spreads through two huge bubbles filled with fast electrons and magnetic fields, making the lobes glow in radio waves.',a:'A water jet makes a bright splash where it hits, then pushes water out around the impact point.',cap:'Hotspots mark where the jets hit; the radio lobes grow around them.',note:'Here, hotspot means a jet-impact region near a lobe. The bright point at the galaxy’s centre is called the radio core, not a hotspot.',button:'Replay the story'}
];let g3Step=0;
function setStep(i){g3Step=i;const s=steps[i];$('agnScene').className=`agn-scene step-${i}`;$('g3Kicker').textContent=s.k;$('g3Title').textContent=s.t;$('g3Copy').textContent=s.c;$('g3Analogy').textContent=s.a;$('g3Honesty').textContent=s.note;$('g3SceneCaption').textContent=s.cap;$('g3Next').innerHTML=`${s.button} <span>→</span>`;$('g3Score').textContent=`${i}/5`;$$('#g3Steps button').forEach((b,j)=>{b.classList.toggle('active',j===i);b.classList.toggle('done',j<i)});if(i===4){$('g3Score').textContent='5/5';toast('Energy journey complete!')}}
$$('#g3Steps button').forEach(b=>b.onclick=()=>setStep(Number(b.dataset.step)));$('g3Next').onclick=()=>setStep(g3Step===4?0:g3Step+1);

// Game 4 — schematic antenna-pair sampling in the u–v plane
const arraySvg=$('arraySvg'),antennas=[{x:200,y:250},{x:400,y:190}];let rotated=false;
function svgEl(tag,attrs){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function renderArray(){const ag=$('antennaGroup'),bg=$('baselineGroup');ag.innerHTML='';bg.innerHTML='';for(let i=0;i<antennas.length;i++)for(let j=i+1;j<antennas.length;j++)bg.append(svgEl('line',{x1:antennas[i].x,y1:antennas[i].y,x2:antennas[j].x,y2:antennas[j].y,stroke:'#ee5a3a','stroke-width':'2','stroke-dasharray':'5 5',opacity:'.55'}));antennas.forEach((a,i)=>{const g=svgEl('g',{transform:`translate(${a.x} ${a.y})`});g.append(svgEl('path',{d:'M-18 -12 Q0 12 18 -12',fill:'#fff9ec',stroke:'#2a2521','stroke-width':'4'}));g.append(svgEl('line',{x1:0,y1:3,x2:0,y2:25,stroke:'#2a2521','stroke-width':'4'}));const t=svgEl('text',{x:0,y:42,'text-anchor':'middle'});t.textContent=String(i+1);g.append(t);ag.append(g)});const pairs=antennas.length*(antennas.length-1)/2;$('g4Count').textContent=`${antennas.length} antennas · ${pairs} pair${pairs===1?'':'s'}`;drawInterferometer()}
function samples(){const out=[];for(let i=0;i<antennas.length;i++)for(let j=i+1;j<antennas.length;j++){const dx=antennas[j].x-antennas[i].x,dy=antennas[j].y-antennas[i].y;const angles=rotated?[-.55,-.27,0,.27,.55]:[0];for(const a of angles)out.push([dx*Math.cos(a)-dy*Math.sin(a),dx*Math.sin(a)+dy*Math.cos(a)])}return out}
function drawInterferometer(){const uv=$('uvCanvas').getContext('2d'),pts=samples(),pairs=antennas.length*(antennas.length-1)/2;uv.fillStyle='#fff9ec';uv.fillRect(0,0,520,430);uv.strokeStyle='rgba(42,37,33,.12)';uv.lineWidth=1;[70,140,210].forEach(r=>{uv.beginPath();uv.arc(260,215,r,0,Math.PI*2);uv.stroke()});uv.strokeStyle='rgba(42,37,33,.38)';uv.beginPath();uv.moveTo(260,18);uv.lineTo(260,412);uv.moveTo(24,215);uv.lineTo(496,215);uv.stroke();uv.fillStyle='#2a2521';uv.font='bold 17px Arial';uv.fillText('u',485,206);uv.fillText('v',270,35);uv.font='bold 11px Arial';uv.fillText('LOWER SPATIAL FREQUENCY',273,236);uv.fillText('HIGHER SPATIAL FREQUENCY',325,397);pts.forEach(([u,v])=>{const x=260+u*.34,y=215-v*.34,mx=260-u*.34,my=215+v*.34;uv.strokeStyle='#ee5a3a';uv.lineWidth=2;uv.beginPath();uv.arc(mx,my,5,0,Math.PI*2);uv.stroke();uv.fillStyle='#2766dc';uv.beginPath();uv.arc(x,y,5,0,Math.PI*2);uv.fill()});$('g4Samples').textContent=`${pts.length} measurement${pts.length===1?'':'s'}`;$('g4Total').textContent=String(pts.length);$('g4Caption').textContent=rotated?`${pairs} antenna pair${pairs===1?'':'s'} observed at five schematic times: ${pts.length} visibility measurements. The hollow dots are conjugate mirrors, not extra measurements.`:`${pairs} antenna pair${pairs===1?'':'s'} at one moment: ${pts.length} visibility measurement${pts.length===1?'':'s'}. Add an antenna or let Earth rotate to sample more.`}
function addAntenna(x,y){if(antennas.length>=10){toast('Array full — now rotate the Earth!');return}antennas.push({x:Math.max(35,Math.min(565,x)),y:Math.max(35,Math.min(380,y))});rotated=false;renderArray()}
arraySvg.addEventListener('click',e=>{const p=arraySvg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(arraySvg.getScreenCTM().inverse());addAntenna(q.x,q.y)});$('g4Add').onclick=()=>{const n=antennas.length,angle=n*2.39,r=75+(n%4)*30;addAntenna(300+Math.cos(angle)*r,215+Math.sin(angle)*r)};$('g4Rotate').onclick=()=>{rotated=true;drawInterferometer();toast('Earth rotation added new u–v samples!')};$('g4Reset').onclick=()=>{antennas.splice(0,antennas.length,{x:200,y:250},{x:400,y:190});rotated=false;renderArray()};

renderArray();setBand('radio');setStep(0);const initial=location.hash.slice(1);showScreen(['game0','game1','game2','game3','game4','summary'].includes(initial)?initial:'home');
